version: '3'
services:
  nginx:
    build: ./docker/nginx
    container_name: collierclient-nginx
    ports:
      - "8000:8000"
    volumes:
      - wwwroot:/wwwroot
  webpack:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: collierclient-node
    environment:
      - API_URL=http://localhost:8080
      - NODE_ENV=development
    ports:
      - "35729:35729" # for live reload
    volumes:
      - .:/client
      - /client/node_modules
      - wwwroot:/client/public
volumes:
  wwwroot:
    driver: local