version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-new
    entrypoint: /wwwroot/docker-entrypoint.js
    container_name: gwiclient-web
    environment:
      API_URL: http://localhost:8080
    ports:
      - "8000:80"
      - "35729:35729" # for live reload
    volumes:
      - .:/wwwroot
      - /wwwroot/node_modules
volumes:
  wwwroot:
    driver: local