FROM node:8.1.4-alpine
RUN npm install webpack -g

RUN mkdir /wwwroot
# RUN mkdir -p /run/nginx
$ COPY ./nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /wwwroot
COPY . /wwwroot
RUN rm -rf ./public/*.bundle.js
# RUN npm install --loglevel warn
CMD [ “NPM run start”]
RUN apk add --no-cache nginx
EXPOSE 80